return {
  "ThePrimeagen/harpoon",
  lazy = true,
  keys = {
    { mode = { "n" }, "<leader>hs", ":Telescope harpoon marks<CR>", desc = "Search Harpoon marks", silent = true },
    {
      mode = { "n" },
      "<leader>hm",
      ":lua require('harpoon.mark').add_file()<CR>",
      desc = "Add Harpoon mark",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>ht",
      ":lua require('harpoon.ui').toggle_quick_menu()<CR>",
      desc = "Toggle Harpoon UI",
      silent = true,
    },
    -- shortcuts
    {
      mode = { "n" },
      "<leader>hh",
      ":lua require('harpoon.ui').nav_file(1)<CR>",
      desc = "Harpoon file 1",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hj",
      ":lua require('harpoon.ui').nav_file(2)<CR>",
      desc = "Harpoon file 2",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hk",
      ":lua require('harpoon.ui').nav_file(3)<CR>",
      desc = "Harpoon file 3",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hl",
      ":lua require('harpoon.ui').nav_file(4)<CR>",
      desc = "Harpoon file 4",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hf",
      ":lua require('harpoon.ui').nav_file(5)<CR>",
      desc = "Harpoon file 5",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hd",
      ":lua require('harpoon.ui').nav_file(6)<CR>",
      desc = "Harpoon file 6",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hs",
      ":lua require('harpoon.ui').nav_file(7)<CR>",
      desc = "Harpoon file 7",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>ha",
      ":lua require('harpoon.ui').nav_file(8)<CR>",
      desc = "Harpoon file 8",
      silent = true,
    },
    -- next/prev
    {
      mode = { "n" },
      "<leader>hn",
      ":lua require('harpoon.ui').nav_next()<CR>",
      desc = "Harpoon next",
      silent = true,
    },
    {
      mode = { "n" },
      "<leader>hp",
      ":lua require('harpoon.ui').nav_prev()<CR>",
      desc = "Harpoon prev",
      silent = true,
    },
  },
}
