return {}
-- local highlight = {
--   "CursorColumn",
--   "Whitespace",
-- }
--
-- return {
--   {
--     "echasnovski/mini.indentscope",
--     enabled = false, -- Removes animations
--   },
--   {
--     "lukas-reineke/indent-blankline.nvim",
--     event = { "BufReadPost", "BufNewFile" },
--     opts = {
--       indent = {
--         char = "│",
--         tab_char = "│",
--       },
--       scope = { enabled = true },
--       exclude = {
--         filetypes = {
--           "help",
--           "alpha",
--           "dashboard",
--           "neo-tree",
--           "Trouble",
--           "lazy",
--           "mason",
--           "notify",
--           "toggleterm",
--           "lazyterm",
--         },
--       },
--       -- show_trailing_blankline_indent = false,
--       -- show_current_context = true,
--       whitespace = {
--         highlight = highlight,
--         remove_blankline_trail = false,
--       },
--     },
--   },
-- }
