env:
  TERM: xterm-256color

window:
  opacity: 0.95 # transparent
  startup_mode: Maximized

  # Make `Option` key behave as `Alt` (macOS only):
  #   - OnlyLeft
  #   - OnlyRight
  #   - Both
  #   - None (default)
  #option_as_alt: None

# Font configuration
font:
  normal:
    family: MesloLGLDZ Nerd Font Mono
    style: Regular

  bold:
    family: MesloLGLDZ Nerd Font Mono
    style: Bold

  italic:
    family: MesloLGLDZ Nerd Font Mono
    style: Italic

  bold_italic:
    family: MesloLGLDZ Nerd Font Mono
    style: Bold Italic

  size: 11

draw_bold_text_with_bright_colors: true
import:
  - ~/repos/tokyonight.nvim/extras/alacritty/tokyonight_storm.yml

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,              mods: Control|Shift, mode: ~Vi,        action: Paste            }
  - { key: C,              mods: Control|Shift,                   action: Copy             }
  - { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
  - { key: Plus,           mods: Control,                         action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                         action: DecreaseFontSize }
  - { key: N,              mods: Control|Shift,                   action: SpawnNewInstance }
