theme = "tokyonight_storm"

[editor]
cursorline = true
color-modes = true
auto-save = true
auto-format = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diagnostics", "line-numbers",  "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.C-y]
y = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE open         > /dev/null"
v = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE vsplit       > /dev/null"
h = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE hsplit       > /dev/null"
Y = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE open    zoom > /dev/null"
V = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE vsplit  zoom > /dev/null"
H = ":sh wezterm cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE hsplit  zoom > /dev/null"

[keys.insert]
C-v = ":primary-clipboard-paste-before"
