theme = "tokyonight_storm"

[editor]
cursorline = true
color-modes = true
auto-save = true
auto-format = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
