theme = "tokyonight_storm"

[editor]
rulers = [80] 
cursorline = true
color-modes = true
auto-save = true
auto-format = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diagnostics", "line-numbers",  "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.insert]
C-v = ":primary-clipboard-paste-before"
