name: "test_cachix"
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: mlflexer
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build the rpi5 flake
      run: nix build .#nixosConfigurations.laptop.config.system.build.toplevel
